name: hello

on: push

jobs:
  hello-hanu:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello Hanu!"

  hello-maulik:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello Maulik!"    