name: hello

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repository
        run: git clone https://github.com/Maulik-0653/Action

      - name: list files
        run: ls -la
           